server:
  port: 8190
shiro:
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
  web:
    enabled: true
  successUrl: /index
  loginUrl: /login
  unauthorizedUrl: /unauth
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro_test
    username: root
    password: 461200
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
